object Message {
    const val START_RESERVATION = "영화 예매를 시작합니다. 새 예매를 생성하시겠습니까? (Y/N)"
    const val INPUT_MOVIE_NAME = "예매할 영화 제목을 입력하세요:"
    const val INVALID_MOVIE_NAME = "해당 영화가 존재하지 않습니다. 다시 입력해주세요."
    const val INPUT_DATE = "날짜를 입력하세요 (YYYY-MM-DD):"
    const val MOVIE_SCREENINGS_LIST = "해당 날짜의 상영 목록"
    const val SELECT_MOVIE_SCREENING = "상영 번호를 선택하세요:"
    const val SEAT_GROUP = "좌석 배치도"
    const val INVALID_SEAT = "해당 좌석은 예매할 수 없습니다."
    const val NO_EXIST_SEAT = "존재하지 않는 좌석입니다."
    const val SHOW_RESERVATION_INFO = "장바구니에 추가됨"
    const val INPUT_CONTINUE = "다른 영화를 추가하시겠습니까? (Y/N)"
    const val INPUT_POINT = "사용할 포인트를 입력하세요 (없으면 0):"
    const val SELECT_PAY_TYPE = "결제 수단을 선택하세요:"
    const val INVALID_PAY_TYPE = "존재하지 않는 결제 수단입니다."
    const val TOTAL_PRICE_TITLE = "가격 계산"
    const val TOTAL_PRICE = "최종 결제 금액:"
    const val INPUT_CONFIRM_PAYMENT = "위 금액으로 결제하시겠습니까? (Y/N)"
}
