package domain.backend.repository.support

import java.sql.Connection

object SchemaInitializer {
    fun initialize(isLocal: Boolean) {
        H2ConnectionFactory.connection(isLocal).use { connection -> initialize(connection) }
    }

    fun initializeWithUrl(url: String) {
        H2ConnectionFactory.connection(url).use { connection -> initialize(connection) }
    }

    private fun initialize(connection: Connection) {
        connection.createStatement().use { statement ->
            statement.executeUpdate(
                """
                CREATE TABLE IF NOT EXISTS movie (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    title VARCHAR(120) NOT NULL UNIQUE,
                    running_minutes BIGINT NOT NULL
                )
                """.trimIndent(),
            )

            statement.executeUpdate(
                """
                CREATE TABLE IF NOT EXISTS screening (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    movie_id BIGINT NOT NULL,
                    screening_date DATE NOT NULL,
                    start_time TIME NOT NULL,
                    UNIQUE (movie_id, screening_date, start_time),
                    CONSTRAINT fk_screening_movie
                        FOREIGN KEY (movie_id) REFERENCES movie(id)
                )
                """.trimIndent(),
            )

            statement.executeUpdate(
                """
                CREATE TABLE IF NOT EXISTS reservation (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    screening_id BIGINT NOT NULL,
                    seat_row VARCHAR(1) NOT NULL,
                    seat_column INT NOT NULL,
                    reserved_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE (screening_id, seat_row, seat_column),
                    CONSTRAINT fk_reservation_screening
                        FOREIGN KEY (screening_id) REFERENCES screening(id)
                        ON DELETE CASCADE
                )
                """.trimIndent(),
            )
        }
    }
}
